const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"/>',chat:'<path d="M21 11.5a9 9 0 0 1-9.5 9L3 22l1.5-7A9 9 0 1 1 21 11.5Z"/><path d="M8 9h8m-8 5h5"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v5m10-5v5M3 11h18m-13 5h2m4 0h2"/>',mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-3 0h6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',arrow:'<path d="M12 20V4m-6 6 6-6 6 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',video:'<rect x="2" y="6" width="13" height="13" rx="3"/><path d="m15 10 6-3v11l-6-3"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5zm4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14z"/>'};
const ic=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.spark}</svg>`;
icons.folder='<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>';
icons.plus='<path d="M12 5v14M5 12h14"/>';
icons.back='<path d="m14 5-7 7 7 7"/>';
icons.file='<path d="M14 2H5v20h14V7zm0 0v5h5M8 12h8m-8 4h6"/>';
icons.tasks='<rect x="3" y="4" width="18" height="17" rx="3"/><path d="m6 10 2 2 3-4m2 3h4m-10 6h10"/>';
icons.more='<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>';
icons.pause='<path d="M8 5v14M16 5v14"/>';
icons.pin='<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>';
icons.pushpin='<path d="m9 3 6 0-1 6 4 4H6l4-4zm3 10v8"/>';
icons.reply='<path d="m9 5-6 6 6 6m-6-6h11a7 7 0 0 1 7 7"/>';
icons.send='<path d="m3 3 18 9-18 9 4-9zm4 9h14"/>';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TODAY='2026-09-11';
const initial={user:'Tomasz',serial:20,
 people:[
 {id:0,name:'Olena Kovalenko',initials:'OK',language:'Ukraiński',locale:'uk-UA',topic:'Wezwanie na przesłuchanie',stage:'Klient',owner:'Tomasz',urgent:false,needsReply:false,source:'Formularz WWW',created:'2026-09-09',description:'Klientka otrzymała wezwanie na przesłuchanie. Chce omówić dokumenty i przygotować się do spotkania.',incoming:'Дякую, надішлю документи до зустрічі.',translation:'Dziękuję, prześlę dokumenty przed spotkaniem.',time:'09:15'},
 {id:1,name:'Andrii Melnyk',initials:'AM',language:'Ukraiński',locale:'uk-UA',topic:'Zatrzymanie osoby bliskiej',stage:'Nowy',owner:'Nieprzypisany',urgent:true,needsReply:true,source:'Formularz WWW',created:TODAY,description:'Prośba o pilny kontakt w sprawie zatrzymania brata. Informacje o miejscu zatrzymania do ustalenia podczas rozmowy.',incoming:'Доброго дня, мого брата затримали. Чи можете допомогти?',translation:'Dzień dobry, zatrzymano mojego brata. Czy może Pan pomóc?',time:'09:29'},
 {id:2,name:'Maria Sokołowa',initials:'MS',language:'Rosyjski',locale:'ru-RU',topic:'Konsultacja prawna',stage:'Nowy',owner:'Nieprzypisany',urgent:false,needsReply:true,source:'Formularz WWW',created:TODAY,description:'Klientka umówiła konsultację przez stronę. Preferuje rozmowę po rosyjsku i kontakt przez WhatsApp.',incoming:'Здравствуйте! Можно провести консультацию на русском?',translation:'Dzień dobry! Czy konsultacja może odbyć się po rosyjsku?',time:'09:03'},
 {id:3,name:'Dmytro Bondarenko',initials:'DB',language:'Polski',locale:'pl-PL',topic:'Omówienie dokumentów',stage:'Klient',owner:'Paweł',urgent:false,needsReply:false,source:'Polecenie',created:'2026-09-07',description:'Klient przekazał dokumenty do omówienia podczas konsultacji. Kolejne działania do ustalenia po spotkaniu.',incoming:'Dziękuję, przesłałem komplet dokumentów. Do zobaczenia o 12:00.',translation:'',time:'08:42'}],
 cases:[{id:10,personId:0,title:'Przygotowanie do przesłuchania',number:'KR / 2026 / 041',owner:'Tomasz',status:'W toku',summary:'Zapoznanie się z wezwaniem i konsultacja przed przesłuchaniem.',created:'2026-09-09'}, {id:11,personId:3,title:'Analiza dokumentów klienta',number:'KR / 2026 / 038',owner:'Paweł',status:'Oczekujemy na klienta',summary:'Weryfikacja przekazanych dokumentów i ustalenie dalszego zakresu prowadzenia sprawy.',created:'2026-09-07'}],
 events:[{id:12,personId:0,caseId:10,title:'Konsultacja z Oleną',date:TODAY,time:'10:30',duration:30,owner:'Tomasz',type:'Konsultacja',status:'Potwierdzona',place:'Online'}, {id:13,personId:3,caseId:11,title:'Omówienie dokumentów',date:TODAY,time:'12:00',duration:30,owner:'Paweł',type:'Konsultacja',status:'Potwierdzona',place:'Kancelaria'}, {id:14,personId:1,caseId:null,title:'Pierwsza konsultacja',date:TODAY,time:'14:00',duration:30,owner:'Nieprzypisany',type:'Konsultacja',status:'Do potwierdzenia',place:'Telefon'}, {id:15,personId:2,caseId:null,title:'Pierwsza konsultacja',date:'2026-09-12',time:'11:00',duration:60,owner:'Nieprzypisany',type:'Konsultacja',status:'Do potwierdzenia',place:'Online'}, {id:16,personId:0,caseId:10,title:'Przesłuchanie klientki',date:'2026-09-15',time:'09:00',duration:60,owner:'Tomasz',type:'Termin w sprawie',status:'Potwierdzona',place:'Warszawa · miejsce do sprawdzenia'}],
 tasks:[{id:17,personId:1,caseId:null,title:'Oddzwonić w sprawie zatrzymania',date:TODAY,owner:'Tomasz',done:false,priority:'Pilne'}, {id:18,personId:0,caseId:10,title:'Zapoznać się z wezwaniem',date:TODAY,owner:'Tomasz',done:false,priority:'Zwykłe'}, {id:19,personId:3,caseId:11,title:'Uzupełnić notatkę po konsultacji',date:TODAY,owner:'Paweł',done:false,priority:'Zwykłe'}],
 notes:[{id:1,personId:0,caseId:10,text:'Klientka potwierdziła język ukraiński. Na konsultacji sprawdzić kompletność przekazanych dokumentów.',author:'Tomasz',date:'2026-09-10'}, {id:2,personId:3,caseId:11,text:'Dokumenty otrzymane. Do omówienia podczas konsultacji w piątek.',author:'Paweł',date:'2026-09-10'}],
 messages:{0:[],1:[],2:[],3:[]},
 activity:[{id:1,personId:0,caseId:10,text:'Konsultacja potwierdzona na 10:30',date:TODAY,author:'Tomasz'},{id:2,personId:3,caseId:11,text:'Dodano notatkę do sprawy',date:'2026-09-10',author:'Paweł'}]
};
let data=structuredClone(initial);try{const d=JSON.parse(sessionStorage.getItem('emma-workspace-v3'));if(d&&d.version===3&&Array.isArray(d.people)&&Array.isArray(d.cases)&&Array.isArray(d.events)&&Array.isArray(d.tasks)&&Array.isArray(d.notes)&&d.messages&&Array.isArray(d.activity))data=d}catch{}
let screen='home',selectedId=null,history=[],clientMode='Leady',clientFilter='Wszystkie',caseFilter='Aktywne',search='',taskFilter='Otwarte',taskOwner='Obaj',day=TODAY,week='2026-09-07',calendarOwner='Obaj',chatFilter='Wszystkie',caseTab='Przegląd';
let chatSearch='',firstUnreadId=null;
let emmaContext=null,emmaTurns=[],pendingAction=null,emmaInput='',voiceState='ready',voiceMessage='',rec=null,voiceToken=0,speechToken=0,speakReplies=true,awaitingInput=null,voiceTimer=null,modalBack=null;
const person=id=>id==null?undefined:data.people.find(p=>p.id===Number(id)),caseBy=id=>id==null?undefined:data.cases.find(c=>c.id===Number(id)),eventBy=id=>id==null?undefined:data.events.find(e=>e.id===Number(id));
const nextId=()=>++data.serial;
const linkedCase=id=>data.cases.find(c=>c.personId===Number(id)&&c.status!=='Zamknięta');
const waiting=()=>data.people.filter(p=>p.needsReply),openTasks=()=>data.tasks.filter(t=>!t.done),activeCases=()=>data.cases.filter(c=>c.status!=='Zamknięta');
const sortEvents=arr=>[...arr].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
function persist(){try{sessionStorage.setItem('emma-workspace-v3',JSON.stringify({...data,version:3}))}catch{toast('Zmiany pozostaną tylko do zamknięcia strony.')}}
function record(text,personId=null,caseId=null){data.activity.unshift({id:nextId(),text,personId,caseId,date:TODAY,author:data.user})}
function plural(n,a,b,c){return `${n} ${n===1?a:n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?b:c}`}
const dateText=d=>d===TODAY?'Dzisiaj':d==='2026-09-12'?'Jutro':new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
function addDays(d,n){let x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
function toast(text){document.querySelectorAll('[data-toast]').forEach(e=>{e.textContent=text;e.classList.add('visible')});clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>document.querySelectorAll('[data-toast]').forEach(e=>e.classList.remove('visible')),3800)}
function avatar(p){return `<span class="avatar tone-${p.id}" aria-hidden="true">${esc(p.initials)}</span>`}
function personRow(p,sub=p.topic,arrow=true){return `<div class="person">${avatar(p)}<div><b>${esc(p.name)}</b><p>${esc(sub)}</p></div>${arrow?ic('chevron'):''}</div>`}
function chip(text,tone=''){return `<span class="pill ${tone}">${esc(text)}</span>`}
function heading(kicker,title,button=''){return `<header><div><span class="date">${kicker}</span><h1 class="welcome">${title}</h1></div>${button}</header>`}
function section(title,action='',call=''){return `<div class="section-head"><h2>${title}</h2>${action?`<button class="text-button" onclick="${call}">${action}</button>`:''}</div>`}
function backHeader(title,subtitle,more=''){return `<div class="back-header"><button class="icon-button" onclick="back()" aria-label="Wróć">${ic('back')}</button><div><span>${subtitle}</span><b>${title}</b></div>${more}</div>`}
function segments(values,current,handler){return `<div class="segmented" role="group">${values.map(x=>`<button aria-pressed="${x===current}" class="${x===current?'selected':''}" onclick="${handler}('${x}')">${x}</button>`).join('')}</div>`}
function go(s,id=null,push=true){stopVoice();if($('#sheet').open)closeSheet();if(push&&(screen!==s||selectedId!==id))history.push({screen,id:selectedId,scroll:$('#content').scrollTop});screen=s;selectedId=id;firstUnreadId=null;if(s==='chat'){firstUnreadId=threadMessages(id).find(m=>m.direction==='in'&&!m.readBy.includes(data.user))?.id??null;readChat(id)}render();$('#content').scrollTop=0;if(s==='chat')requestAnimationFrame(()=>{if(firstUnreadId!==null)$('#unread-divider')?.scrollIntoView({block:'center'});else scrollChat()})}
function back(){const last=history.pop();if(!last){go('home',null,false);return}go(last.screen,last.id,false);$('#content').scrollTop=last.scroll||0}
function selectClients(mode){clientMode=mode;go('clients')}
function setClientMode(m){clientMode=m;search='';clientFilter='Wszystkie';render()}
function nav(){const current=['case','person','clients'].includes(screen)?'clients':screen==='chat'?'messages':screen==='tasks'?'home':screen;const tabs=[['home','Dzisiaj','home'],['clients','Klienci','people'],['emma','Emma','spark'],['messages','Rozmowy','chat'],['calendar','Kalendarz','calendar']];$('#nav').innerHTML=tabs.map(([id,label,icon])=>`<button onclick="go('${id}')" class="${current===id?'active':''}" ${current===id?'aria-current="page"':''}>${id==='emma'?`<span class="nav-emma">${ic(icon)}</span>`:ic(icon)}<span>${label}</span>${id==='messages'&&unreadTotal()?`<span class="nav-unread" aria-label="${unreadTotal()} nieprzeczytane wiadomości">${unreadTotal()}</span>`:''}</button>`).join('')}
function home(){const events=sortEvents(data.events.filter(e=>e.date===TODAY&&e.type==='Konsultacja')),mine=events.find(e=>e.owner===data.user&&e.status!=='Zakończona'),urgent=waiting().find(p=>p.urgent),tasks=openTasks().filter(t=>t.date<=TODAY);return `${heading('PIĄTEK, 11 WRZEŚNIA',`Dzień dobry, ${data.user==='Tomasz'?'Tomaszu':'Pawle'}`,`<button class="avatar user-avatar" onclick="profile()" aria-label="Profil i zespół">${data.user==='Tomasz'?'TR':'PR'}</button>`)}<section class="emma-card"><div class="emma-top"><div class="orb" aria-hidden="true"></div><b>Emma</b><button class="brief-listen" onclick="openEmma(null,'brief')" aria-label="Odsłuchaj briefing">${ic('sound')}</button></div><p>${urgent?`<strong>${urgent.name.split(' ')[0]} czeka na pilny kontakt.</strong><br>W Twoim kalendarzu: ${plural(events.filter(e=>e.owner===data.user).length,'konsultacja','konsultacje','konsultacji')}.`:`<strong>Twój dzień jest uporządkowany.</strong><br>${plural(tasks.length,'zadanie do wykonania','zadania do wykonania','zadań do wykonania')} w zespole.`}</p><button class="voice-cta" onclick="openEmma(null,null,true)">${ic('mic')} Porozmawiaj z Emmą</button></section><div class="workspace-stats"><button onclick="selectClients('Leady')"><b>${data.people.filter(p=>p.stage!=='Klient').length}</b><span>Leady</span></button><button onclick="selectClients('Sprawy')"><b>${activeCases().length}</b><span>Prowadzone sprawy</span></button><button onclick="go('tasks')"><b>${tasks.length}</b><span>Zadania na dziś</span></button></div>${section('Najbliższa konsultacja','Kalendarz',"go('calendar')")}${mine?meetingCard(mine):'<div class="card empty">Nie masz już dziś zaplanowanych konsultacji.</div>'}${section('Do załatwienia','Wszystkie',"go('tasks')")}<div class="card task-group">${tasks.slice(0,3).map(taskRow).join('')||'<div class="empty">Wszystkie zadania na dziś wykonane.</div>'}</div>${section('Prowadzone sprawy','Zobacz wszystkie',"selectClients('Sprawy')")}${activeCases().slice(0,2).map(caseCard).join('')}`}
function meetingCard(e){const p=person(e.personId);return `<button class="card meeting" onclick="eventDetail(${e.id})"><div class="meeting-top">${chip(e.status,e.status==='Potwierdzona'?'green':e.status==='Zakończona'?'':'amber')}<span>${e.time} · ${e.duration} min</span></div>${personRow(p,e.title)}<div class="meeting-foot"><span>${ic(e.place==='Online'?'video':'pin')} ${esc(e.place)}</span><span>${ic('people')} ${esc(e.owner)}</span></div></button>`}
function taskRow(t){const p=person(t.personId);return `<div class="task-row ${t.done?'completed':''}"><button class="task-check" onclick="toggleTask(${t.id})" aria-label="${t.done?'Oznacz jako niewykonane':'Wykonaj'}: ${esc(t.title)}" aria-pressed="${t.done}">${t.done?ic('check'):''}</button><button class="task-body" onclick="taskDetail(${t.id})"><b>${esc(t.title)}</b><span>${p?esc(p.name):'Kancelaria'} · ${esc(t.owner)}</span></button><span class="task-date ${t.priority==='Pilne'&&!t.done?'urgent':''}">${t.priority==='Pilne'&&!t.done?'Pilne':dateText(t.date)}</span></div>`}
function caseCard(c){const p=person(c.personId),n=data.tasks.filter(t=>t.caseId===c.id&&!t.done).length,next=sortEvents(data.events.filter(e=>e.caseId===c.id&&e.date>=TODAY&&e.status!=='Zakończona'))[0];return `<button class="card case-card" onclick="caseTab='Przegląd';go('case',${c.id})"><div class="case-card-head"><span>${c.number}</span>${chip(c.status,c.status==='W toku'?'green':'')}</div><h3>${esc(c.title)}</h3><p>${esc(p.name)} · ${esc(c.owner)}</p><div class="case-card-foot"><span>${ic('tasks')} ${plural(n,'zadanie','zadania','zadań')}</span>${next?`<span>${ic('calendar')} ${dateText(next.date)}, ${next.time}</span>`:'<span>Brak kolejnego terminu</span>'}</div></button>`}
function clients(){return `${heading('BAZA KANCELARII','Klienci',`<button class="icon-button bordered" onclick="newLead()" aria-label="Dodaj leada">${ic('plus')}</button>`)}${segments(['Leady','Sprawy'],clientMode,'setClientMode')}<label class="search">${ic('search')}<input aria-label="Szukaj klienta, sprawy lub tematu" placeholder="Szukaj osoby lub tematu" value="${esc(search)}" oninput="search=this.value;document.querySelector('#client-list').innerHTML=clientList()"></label><div class="filter-chips">${(clientMode==='Leady'?['Wszystkie','Nowe','W kontakcie']:['Aktywne','Zamknięte']).map(f=>`<button class="${(clientMode==='Leady'?clientFilter:caseFilter)===f?'selected':''}" aria-pressed="${(clientMode==='Leady'?clientFilter:caseFilter)===f}" onclick="setClientFilter('${f}')">${f}</button>`).join('')}</div><div id="client-list">${clientList()}</div>`}
function setClientFilter(f){if(clientMode==='Leady')clientFilter=f;else caseFilter=f;render()}
function clientList(){const q=search.toLocaleLowerCase('pl');if(clientMode==='Sprawy'){const cs=data.cases.filter(c=>(caseFilter==='Zamknięte'?c.status==='Zamknięta':c.status!=='Zamknięta')&&`${c.title} ${c.number} ${person(c.personId).name}`.toLocaleLowerCase('pl').includes(q));return cs.map(caseCard).join('')||emptyState('Brak pasujących spraw','Zmień filtr lub utwórz sprawę z karty klienta.')};const ps=data.people.filter(p=>p.stage!=='Klient'&&(clientFilter==='Wszystkie'||clientFilter==='Nowe'&&p.stage==='Nowy'||clientFilter==='W kontakcie'&&p.stage==='W kontakcie')&&`${p.name} ${p.topic}`.toLocaleLowerCase('pl').includes(q));return ps.map(p=>{const e=sortEvents(data.events.filter(e=>e.personId===p.id&&e.status!=='Zakończona'))[0];return `<button class="card large-lead" onclick="go('person',${p.id})"><div class="meta">${chip(p.urgent&&p.needsReply?'Pilny kontakt':p.stage,p.urgent&&p.needsReply?'amber':'')}<span>${esc(p.language)}</span></div>${personRow(p)}<div class="meta"><span>${e?dateText(e.date)+', '+e.time:'Termin do ustalenia'}</span><span>${esc(p.owner)}</span></div></button>`}).join('')||emptyState('Brak zgłoszeń w tym widoku','Wybierz inny filtr lub dodaj nowy kontakt.')}
function emptyState(title,text){return `<div class="empty card"><b>${title}</b><p>${text}</p></div>`}
function personPage(){const p=person(selectedId),c=linkedCase(p.id),events=sortEvents(data.events.filter(e=>e.personId===p.id)),notes=data.notes.filter(n=>n.personId===p.id);return `${backHeader('Karta klienta',p.source,`<button class="icon-button" onclick="assignPerson(${p.id})" aria-label="Zmień opiekuna">${ic('people')}</button>`)}<div class="client-hero">${avatar(p)}<h1>${esc(p.name)}</h1><p>${esc(p.topic)}</p><div>${chip(p.stage)}${chip(p.language)}${p.urgent&&p.needsReply?chip('Pilny kontakt','amber'):''}</div></div><div class="quick-actions"><button onclick="go('chat',${p.id})">${ic('chat')}<span>WhatsApp</span></button><button onclick="openEmma(${p.id})">${ic('spark')}<span>Emma</span></button><button onclick="noteForm(${p.id},${c?.id??null})">${ic('edit')}<span>Notatka</span></button><button onclick="eventForm(${p.id},${c?.id??null})">${ic('calendar')}<span>Umów</span></button></div><div class="info-list"><div><span>Opiekun</span><button onclick="assignPerson(${p.id})">${esc(p.owner)} ${ic('chevron')}</button></div><div><span>Źródło</span><b>${esc(p.source)}</b></div><div><span>Kontakt od</span><b>${dateText(p.created)}</b></div></div>${c?`<button class="linked-case" onclick="caseTab='Przegląd';go('case',${c.id})">${ic('folder')}<span><small>${c.number}</small><b>${esc(c.title)}</b></span>${ic('chevron')}</button>`:`<button class="primary" onclick="caseForm(${p.id})">${ic('folder')} Rozpocznij prowadzenie sprawy</button>`}${section('Zgłoszenie')}<div class="card prose-card"><p>${esc(p.description)}</p></div>${section('Konsultacje i terminy','Dodaj',`eventForm(${p.id},${c?.id??null})`)}${events.map(e=>`<button class="event-row card" onclick="eventDetail(${e.id})"><span class="event-time">${e.time}<small>${dateText(e.date)}</small></span><span><b>${esc(e.title)}</b><small>${esc(e.status)} · ${esc(e.owner)}</small></span>${ic('chevron')}</button>`).join('')||'<p class="empty">Nie ustalono jeszcze terminu.</p>'}${section('Notatki','Dodaj',`noteForm(${p.id},${c?.id??null})`)}${notes.length?notes.map(noteCard).join(''):emptyState('Pierwsza rozmowa przed Tobą','Dodaj ustalenia po kontakcie z klientem.')}`}
function noteCard(n){return `<article class="card note-card"><div><span>${esc(n.author)}</span><span>${dateText(n.date)}</span></div><p>${esc(n.text)}</p></article>`}
function casePage(){const c=caseBy(selectedId),p=person(c.personId),tasks=data.tasks.filter(t=>t.caseId===c.id),events=sortEvents(data.events.filter(e=>e.caseId===c.id)),notes=data.notes.filter(n=>n.caseId===c.id);return `${backHeader(c.number,'PROWADZONA SPRAWA',`<button class="icon-button" onclick="caseSettings(${c.id})" aria-label="Zmień status i opiekuna sprawy">${ic('more')}</button>`)}<section class="case-title">${chip(c.status,c.status==='W toku'?'green':'')}<h1>${esc(c.title)}</h1><button onclick="go('person',${p.id})">${avatar(p)}<span>${esc(p.name)}<small>Opiekun: ${esc(c.owner)}</small></span>${ic('chevron')}</button></section><button class="case-emma" onclick="openEmma(${p.id},'case')"><div class="orb"></div><span><b>Przygotuj mnie do tej sprawy</b><small>Emma · notatki, terminy, kolejne kroki</small></span>${ic('sound')}</button>${segments(['Przegląd','Zadania','Notatki','Historia'],caseTab,'setCaseTab')}${caseTab==='Przegląd'?`<div class="card prose-card"><h3>Zakres sprawy</h3><p>${esc(c.summary)}</p></div>${section('Kolejny termin','Dodaj',`eventForm(${p.id},${c.id})`)}${events.filter(e=>e.date>=TODAY&&e.status!=='Zakończona').slice(0,2).map(meetingCard).join('')||emptyState('Brak kolejnego terminu','Dodaj konsultację lub termin dotyczący sprawy.')}${section('Otwarte zadania','Dodaj',`taskForm(${p.id},${c.id})`)}<div class="card task-group">${tasks.filter(t=>!t.done).map(taskRow).join('')||'<div class="empty">Wszystkie zadania wykonane.</div>'}</div>${section('Ostatnia notatka','Dodaj',`noteForm(${p.id},${c.id})`)}${notes.length?noteCard(notes.at(-1)):emptyState('Brak notatek','Zapisz lub podyktuj ustalenia z klientem.')}`:caseTab==='Zadania'?`${section('Lista zadań','Dodaj',`taskForm(${p.id},${c.id})`)}<div class="card task-group">${tasks.map(taskRow).join('')||'<div class="empty">Brak zadań w tej sprawie.</div>'}</div>`:caseTab==='Notatki'?`${section('Ustalenia i notatki','Dodaj',`noteForm(${p.id},${c.id})`)}${notes.map(noteCard).join('')||emptyState('Brak notatek','Dodaj pierwsze ustalenia z klientem.')}`:`${section('Historia sprawy')}<div class="activity-list">${data.activity.filter(a=>a.caseId===c.id).map(activityRow).join('')||'<div class="empty">Brak zdarzeń w historii.</div>'}</div>`}`}
function setCaseTab(t){caseTab=t;render()}
function activityRow(a){return `<div class="activity-row"><span class="activity-marker"></span><div><p>${esc(a.text)}</p><small>${esc(a.author)} · ${dateText(a.date)}</small></div></div>`}
function tasksPage(){const ts=data.tasks.filter(t=>(taskFilter==='Wszystkie'||taskFilter==='Otwarte'&&!t.done||taskFilter==='Wykonane'&&t.done)&&(taskOwner==='Obaj'||t.owner===taskOwner)).sort((a,b)=>a.date.localeCompare(b.date));return `${heading('WSPÓLNA LISTA','Zadania',`<button class="icon-button bordered" onclick="taskForm()" aria-label="Dodaj zadanie">${ic('plus')}</button>`)}${segments(['Otwarte','Wykonane','Wszystkie'],taskFilter,'setTaskFilter')}${segments(['Obaj','Tomasz','Paweł'],taskOwner,'setTaskOwner')}<div class="card task-group">${ts.map(taskRow).join('')||'<div class="empty">Brak zadań w tym widoku.</div>'}</div>`}
function setTaskFilter(x){taskFilter=x;render()}function setTaskOwner(x){taskOwner=x;render()}
function toggleTask(id){const t=data.tasks.find(t=>t.id===id);t.done=!t.done;record(`${t.done?'Wykonano':'Przywrócono'} zadanie: ${t.title}`,t.personId,t.caseId);persist();render()}
function calendar(){const days=Array.from({length:7},(_,i)=>addDays(week,i)),events=sortEvents(data.events.filter(e=>e.date===day&&(calendarOwner==='Obaj'||e.owner===calendarOwner)));const month=new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));return `${heading('WSPÓLNY PLAN',month.charAt(0).toUpperCase()+month.slice(1),`<button class="icon-button bordered" onclick="eventForm()" aria-label="Dodaj termin">${ic('plus')}</button>`)}${segments(['Obaj','Tomasz','Paweł'],calendarOwner,'setCalendarOwner')}<div class="week-controls"><button class="icon-button" onclick="shiftWeek(-7)" aria-label="Poprzedni tydzień">${ic('back')}</button><button class="text-button" onclick="calendarToday()">Wróć do dzisiaj</button><button class="icon-button" onclick="shiftWeek(7)" aria-label="Następny tydzień">${ic('chevron')}</button></div><div class="days">${days.map((d,i)=>`<button class="day ${d===day?'selected':''}" aria-pressed="${d===day}" onclick="day='${d}';render()"><span>${['Pn','Wt','Śr','Cz','Pt','So','Nd'][i]}</span><b>${Number(d.slice(-2))}</b><i class="${data.events.some(e=>e.date===d&&(calendarOwner==='Obaj'||e.owner===calendarOwner))?'has-event':''}"></i></button>`).join('')}</div>${section(dateText(day))}${events.map(e=>`<div class="calendar-event">${meetingCard(e)}</div>`).join('')||emptyState('Wolny termin','Nie ma wydarzeń w wybranym dniu.')}<button class="secondary full" onclick="eventForm()">${ic('plus')} Dodaj termin na ten dzień</button>`}
function setCalendarOwner(x){calendarOwner=x;render()}function shiftWeek(n){week=addDays(week,n);day=addDays(day,n);render()}function calendarToday(){week='2026-09-07';day=TODAY;render()}
// Messaging state is separate from whether a client still needs a reply.
function ensureChats(){
 data.chatHistory??={};data.chatPrefs??={};
 for(const p of data.people){
  if(!data.chatHistory[p.id]){
   const readBy=p.needsReply?[]:['Tomasz','Paweł'];
   data.chatHistory[p.id]=p.incoming?[{id:-100-p.id,direction:'in',text:p.incoming,translation:p.translation,date:TODAY,time:p.time,readBy}]:[];
   if(p.id===1)data.chatHistory[p.id].push({id:-201,direction:'in',text:'Можу зараз говорити по телефону.',translation:'Mogę teraz porozmawiać przez telefon.',date:TODAY,time:'09:31',readBy:[]});
   if(p.id===0||p.id===3)data.chatHistory[p.id].push({id:-300-p.id,direction:'out',text:p.id===0?'Дякую. До зустрічі о 10:30.':'Dziękuję, do zobaczenia w kancelarii.',date:TODAY,time:p.id===0?'09:18':'08:45',status:p.id===0?'read':'delivered',author:p.id===0?'Tomasz':'Paweł'});
  }
  for(const m of data.messages[p.id]||[]){m.direction='out';m.date??=TODAY;m.time??='09:41';m.status??='sent';m.author??=data.user}
 }
}
function chatPref(id){data.chatPrefs??={};const mine=data.chatPrefs[data.user]??={};return mine[id]??={pinned:false,unread:false,draft:'',quote:null}}
function threadMessages(id){return [...(data.chatHistory?.[id]||[]),...(data.messages[id]||[])].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)||a.id-b.id)}
function unreadCount(id){const n=threadMessages(id).filter(m=>m.direction==='in'&&!m.readBy.includes(data.user)).length;return Math.max(n,chatPref(id).unread?1:0)}
function unreadTotal(){return data.people.reduce((n,p)=>n+unreadCount(p.id),0)}
function readChat(id){for(const m of threadMessages(id))if(m.direction==='in'&&!m.readBy.includes(data.user))m.readBy.push(data.user);chatPref(id).unread=false;persist()}
function chatRows(){const q=chatSearch.trim().toLocaleLowerCase('pl');return data.people.filter(p=>(chatFilter!=='Nieprzeczytane'||unreadCount(p.id)>0)&&(chatFilter!=='Przypięte'||chatPref(p.id).pinned)&&(!q||[p.name,...threadMessages(p.id).map(m=>m.text)].some(t=>t.toLocaleLowerCase('pl').includes(q)))).sort((a,b)=>Number(chatPref(b.id).pinned)-Number(chatPref(a.id).pinned)||((threadMessages(b.id).at(-1)?.date||'')+(threadMessages(b.id).at(-1)?.time||'')).localeCompare((threadMessages(a.id).at(-1)?.date||'')+(threadMessages(a.id).at(-1)?.time||'')))}
function messageStatus(m){const label={sending:'Wysyłanie',sent:'Wysłano',delivered:'Dostarczono',read:'Odczytano'}[m.status]||'Wysłano';return `<span class="receipt ${m.status}" role="img" aria-label="${label}" title="${label}">${m.status==='sending'?ic('clock'):ic('check')}${['delivered','read'].includes(m.status)?ic('check'):''}</span>`}
function messagesPage(){return `${heading('WHATSAPP','Rozmowy',`<button class="icon-button bordered" onclick="newChat()" aria-label="Nowa rozmowa">${ic('edit')}</button>`)}<label class="search chat-search">${ic('search')}<input type="search" aria-label="Szukaj w rozmowach" placeholder="Szukaj osoby lub wiadomości" value="${esc(chatSearch)}" oninput="chatSearch=this.value;updateChatList()"></label>${segments(['Wszystkie','Nieprzeczytane','Przypięte'],chatFilter,'setChatFilter')}<div id="chat-list">${conversationList()}</div><p class="messaging-demo">Wiadomości przykładowe · WhatsApp niepołączony</p>`}
function conversationList(){return `<div class="messenger-list">${chatRows().map(p=>{const m=threadMessages(p.id).at(-1),n=unreadCount(p.id),pref=chatPref(p.id);return `<div class="messenger-row ${n?'unread':''}"><button class="thread-open" onclick="go('chat',${p.id})" aria-label="${esc(p.name)}${n?', '+n+' nieprzeczytane wiadomości':''}">${avatar(p)}<span class="thread-summary"><span class="thread-title"><b>${esc(p.name)}</b><time>${m?(m.date===TODAY?m.time:dateText(m.date)):''}</time></span><span class="thread-preview">${pref.draft?'<em>Szkic:</em> ':m?.direction==='out'?messageStatus(m):''}<span>${esc(pref.draft||m?.text||'Rozpocznij rozmowę')}</span></span></span><span class="thread-markers">${n?`<span class="unread-count">${n}</span>`:''}${pref.pinned?`<span class="pinned-icon" aria-label="Przypięta">${ic('pushpin')}</span>`:''}</span></button><button class="thread-options" aria-label="Opcje rozmowy z ${esc(p.name)}" onclick="chatOptions(${p.id})">${ic('more')}</button></div>`}).join('')||emptyState(chatSearch?'Brak wyników':chatFilter==='Nieprzeczytane'?'Wszystko przeczytane':'Brak przypiętych rozmów',chatSearch?'Spróbuj innego imienia lub fragmentu wiadomości.':chatFilter==='Nieprzeczytane'?'Nowe wiadomości pojawią się tutaj.':'Przypnij rozmowę w jej menu, aby mieć ją pod ręką.')}</div>`}
function updateChatList(){$('#chat-list').innerHTML=conversationList()}
function setChatFilter(f){chatFilter=f;render()}
function newChat(){openSheet('Nowa rozmowa',`<div class="choice-list">${data.people.map(p=>`<button onclick="go('chat',${p.id})"><span>${esc(p.name)}<small>${esc(p.language)}</small></span>${ic('chevron')}</button>`).join('')}</div>`)}
function chatOptions(id){const pref=chatPref(id);openSheet(esc(person(id).name),`<div class="choice-list"><button onclick="toggleChatPin(${id})"><span>${pref.pinned?'Odepnij rozmowę':'Przypnij rozmowę'}</span>${ic('pushpin')}</button><button onclick="toggleChatUnread(${id})"><span>Oznacz jako ${unreadCount(id)?'przeczytaną':'nieprzeczytaną'}</span>${ic('chat')}</button><button onclick="go('person',${id})"><span>Karta klienta</span>${ic('people')}</button></div>`)}
function toggleChatPin(id){chatPref(id).pinned=!chatPref(id).pinned;persist();closeSheet();render()}
function toggleChatUnread(id){if(unreadCount(id))readChat(id);else chatPref(id).unread=true;persist();closeSheet();if(screen==='chat')go('messages',null,false);else render()}
function chatHeader(){const p=person(selectedId);return `<button class="icon-button" onclick="go('messages',null,false)" aria-label="Wróć do rozmów">${ic('back')}</button><button class="thread-person" onclick="go('person',${p.id})">${avatar(p)}<span><b>${esc(p.name)}</b><small>WhatsApp · ${esc(p.language)}</small></span></button><button class="icon-button" onclick="chatOptions(${p.id})" aria-label="Opcje rozmowy">${ic('more')}</button>`}
function chatPage(){const p=person(selectedId),c=linkedCase(p.id),ms=threadMessages(p.id);let prevDate='';return `<button class="thread-context" onclick="${c?`caseTab='Przegląd';go('case',${c.id})`:`go('person',${p.id})`}">${ic('folder')}<span>${esc(c?.title||p.topic)}</span>${ic('chevron')}</button><div class="messenger-thread">${ms.map(m=>{const date=m.date!==prevDate?`<p class="chat-day">${dateText(m.date)}</p>`:'';prevDate=m.date;return date+(m.id===firstUnreadId?'<p id="unread-divider" class="unread-divider">Nowe wiadomości</p>':'')+messageBubble(m,p)}).join('')||emptyState('Nowa rozmowa','Napisz wiadomość albo przygotuj ją z Emmą.')}</div>`}
function messageBubble(m,p){const out=m.direction==='out';return `<article class="chat-message ${out?'outgoing':'incoming'}" id="message-${m.id}">${m.quote?`<div class="quoted-message"><b>${esc(m.quote.author)}</b><span>${esc(m.quote.text)}</span></div>`:''}<p>${esc(m.text)}</p>${m.translation?`<details class="bubble-translation"><summary>Tłumaczenie</summary><p>${esc(m.translation)}</p></details>`:''}<div class="bubble-meta">${out?`<span>${esc(m.author||'Kancelaria')}</span>`:''}<time>${m.time}</time>${out?messageStatus(m):''}<button aria-label="${out?'Szczegóły i odpowiedź':'Odpowiedz na wiadomość'} z ${m.time}" onclick="messageOptions(${p.id},${m.id})">${ic('more')}</button></div></article>`}
function messageOptions(id,mid){const m=threadMessages(id).find(x=>x.id===mid);if(!m)return;openSheet('Wiadomość',`<p class="message-excerpt">${esc(m.text)}</p>${m.direction==='out'?`<p class="message-detail-status">${messageStatus(m)} ${{sending:'Wysyłanie…',sent:'Wysłano',delivered:'Dostarczono',read:'Odczytano'}[m.status]} · ${m.time}</p><p class="field-help">Status przykładowy. WhatsApp nie jest jeszcze połączony.</p>`:''}<button class="secondary full" onclick="quoteMessage(${id},${mid})">${ic('reply')} Odpowiedz na tę wiadomość</button>`)}
function quoteMessage(id,mid){const m=threadMessages(id).find(x=>x.id===mid);if(!m)return;chatPref(id).quote={author:m.direction==='in'?person(id).name:m.author||'Kancelaria',text:m.text};persist();closeSheet();if(screen!=='chat'||selectedId!==id)go('chat',id);else dock();$('#chat-text').focus()}
function clearQuote(){chatPref(selectedId).quote=null;persist();dock();$('#chat-text').focus()}
function chatComposer(){const p=person(selectedId),pref=chatPref(p.id);return `<button class="composer-emma" onclick="openEmma(${p.id},'reply')"><span class="orb"></span> Przygotuj z Emmą ${ic('chevron')}</button>${pref.quote?`<div class="composer-quote"><div><b>Odpowiedź · ${esc(pref.quote.author)}</b><span>${esc(pref.quote.text)}</span></div><button class="icon-button" aria-label="Anuluj odpowiedź na wiadomość" onclick="clearQuote()">${ic('close')}</button></div>`:''}<form class="chat-composer" onsubmit="sendChat(event,${p.id})"><textarea rows="1" id="chat-text" aria-label="Wiadomość do ${esc(p.name)}" placeholder="Wiadomość…" oninput="saveChatDraft(this.value);this.style.height='auto';this.style.height=Math.min(this.scrollHeight,112)+'px'">${esc(pref.draft)}</textarea><button type="button" class="icon-button" onclick="dictate('chat-text','pl-PL')" aria-label="Podyktuj wiadomość po polsku">${ic('mic')}</button><button id="send-chat" class="icon-button send-button" ${!pref.draft.trim()?'disabled':''} aria-label="Wyślij wiadomość w prototypie">${ic('arrow')}</button></form><p id="dictation-status" class="field-status" role="status"></p>`}
function saveChatDraft(text){chatPref(selectedId).draft=text;persist();$('#send-chat').disabled=!text.trim()}
function sendChat(e,id){e.preventDefault();const text=$('#chat-text').value.trim();if(!text)return;stopVoice();const pref=chatPref(id),quote=pref.quote;pref.draft='';pref.quote=null;sendMessage(id,text,quote);render();scrollChat()}
function scrollChat(){requestAnimationFrame(()=>{$('#content').scrollTop=$('#content').scrollHeight})}
function sendMessage(id,text,quote=null){const m={id:nextId(),text,direction:'out',date:TODAY,time:new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}),status:'sending',author:data.user,quote};const last=threadMessages(id).at(-1);if(last&&m.time<last.time)m.time=last.time;(data.messages[id]??=[]).push(m);readChat(id);const p=person(id);p.needsReply=false;if(p.stage==='Nowy')p.stage='W kontakcie';record('Wysłano wiadomość WhatsApp w demo',id,linkedCase(id)?.id??null);persist();const state=data;setTimeout(()=>{if(data===state)advanceReceipt(id,m.id,'sent')},450);setTimeout(()=>{if(data===state)advanceReceipt(id,m.id,'delivered')},1500)}
function advanceReceipt(id,mid,status){const m=(data.messages[id]||[]).find(x=>x.id===mid),order=['sending','sent','delivered','read'];if(!m||order.indexOf(status)<=order.indexOf(m.status))return;m.status=status;persist();if(screen==='chat'&&selectedId===id){const el=$('#message-'+mid+' .receipt');if(el)el.outerHTML=messageStatus(m)}else if(screen==='messages')updateChatList()}

function placeSheet(){const d=$('#sheet'),r=$('.phone').getBoundingClientRect(),border=parseFloat(getComputedStyle($('.phone')).borderLeftWidth)||0,v=window.visualViewport?window.visualViewport.height+window.visualViewport.offsetTop:window.innerHeight;d.style.left=(r.left+border)+'px';d.style.width=(r.width-2*border)+'px';d.style.bottom=Math.max(0,window.innerHeight-Math.min(r.bottom,v)+border)+'px';d.style.maxHeight=Math.max(180,Math.min(r.height*.9,v-Math.max(0,r.top)-18))+'px'}
function openSheet(title,body){stopVoice();const d=$('#sheet');if(!d.open)modalBack=document.activeElement;d.innerHTML=`<div class="sheet-inner"><div class="handle"></div><div class="sheet-header"><h2 id="sheet-title">${title}</h2><button class="close" onclick="closeSheet()" aria-label="Zamknij">${ic('close')}</button></div>${body}<div class="sheet-toast" data-toast role="status"></div></div>`;placeSheet();if(!d.open)d.showModal();d.scrollTop=0}
function closeSheet(){stopVoice();$('#sheet').close();if(modalBack?.isConnected)modalBack.focus();modalBack=null}
function formError(text){const f=$('#form-error');if(f){f.textContent=text;f.focus()}else toast(text)}
function inputField(label,name,value='',type='text',required=true){return `<label class="form-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
function selectField(label,name,options,value){return `<label class="form-field"><span>${label}</span><select name="${name}">${options.map(o=>{const [val,text]=Array.isArray(o)?o:[o,o];return `<option value="${esc(val)}" ${String(value)===String(val)?'selected':''}>${esc(text)}</option>`}).join('')}</select></label>`}
function textareaField(label,name,value='',required=true){return `<label class="form-field"><span>${label}</span><textarea name="${name}" id="field-${name}" rows="4" ${required?'required':''}>${esc(value)}</textarea></label>`}
const formFooter=label=>`<p id="form-error" class="form-error" role="alert" tabindex="-1"></p><button class="primary" type="submit">${ic('check')} ${label}</button>`;
function fields(e){e.preventDefault();return Object.fromEntries(new FormData(e.target))}
function newLead(){openSheet('Nowy kontakt',`<form onsubmit="saveLead(event)">${inputField('Imię i nazwisko','name')}${inputField('Temat zgłoszenia','topic')}${selectField('Język','language',['Polski','Ukraiński','Rosyjski'],'Polski')}${selectField('Opiekun','owner',['Nieprzypisany','Tomasz','Paweł'],'Nieprzypisany')}${textareaField('Kontekst zgłoszenia','description','',false)}${formFooter('Dodaj kontakt')}</form>`)}
function saveLead(e){const f=fields(e);if(!f.name.trim()||!f.topic.trim())return formError('Uzupełnij imię i temat zgłoszenia.');const id=nextId();data.people.push({id,name:f.name.trim(),initials:f.name.trim().split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase(),topic:f.topic.trim(),description:f.description,language:f.language,locale:({'Polski':'pl-PL','Ukraiński':'uk-UA','Rosyjski':'ru-RU'})[f.language],stage:'Nowy',owner:f.owner,urgent:false,needsReply:false,source:'Dodano ręcznie',created:TODAY,incoming:'',translation:'',time:'Teraz'});data.messages[id]=[];record('Dodano kontakt do kancelarii',id);persist();closeSheet();go('person',id)}
function assignPerson(id){openSheet('Opiekun klienta',`<p>${esc(person(id).name)}</p><div class="choice-list">${['Tomasz','Paweł','Nieprzypisany'].map(n=>`<button onclick="savePersonOwner(${id},'${n}')"><span>${n}</span>${person(id).owner===n?ic('check'):ic('chevron')}</button>`).join('')}</div>`)}
function savePersonOwner(id,owner){person(id).owner=owner;record(`Zmieniono opiekuna klienta: ${owner}`,id,linkedCase(id)?.id??null);persist();closeSheet();render();toast('Zmieniono opiekuna klienta. Terminy mają własne przypisania.')}
function caseForm(id){const p=person(id);if(linkedCase(id)){closeSheet();go('case',linkedCase(id).id);return}openSheet('Rozpocznij prowadzenie sprawy',`<div class="form-person">${personRow(p,p.topic,false)}</div><form onsubmit="saveCase(event,${id})">${inputField('Nazwa sprawy','title',p.topic)}${selectField('Prowadzący','owner',['Tomasz','Paweł'],p.owner==='Nieprzypisany'?data.user:p.owner)}${textareaField('Zakres i ustalenia','summary',p.description)}<p class="field-help">Kontakt, konsultacje i dotychczasowe notatki zostaną powiązane z tą sprawą.</p>${formFooter('Utwórz sprawę')}</form>`)}
function saveCase(e,id){const f=fields(e);if(linkedCase(id)){closeSheet();go('case',linkedCase(id).id);return}if(!f.title.trim()||!f.summary.trim())return formError('Uzupełnij nazwę i zakres sprawy.');const cid=nextId(),n=Math.max(41,...data.cases.map(c=>Number(c.number.split('/').at(-1))||0))+1;data.cases.push({id:cid,personId:id,title:f.title.trim(),summary:f.summary.trim(),owner:f.owner,status:'W toku',number:'KR / 2026 / '+String(n).padStart(3,'0'),created:TODAY});person(id).stage='Klient';person(id).owner=f.owner;for(const key of ['notes','tasks','events','activity'])for(const item of data[key])if(item.personId===id&&item.caseId==null)item.caseId=cid;record('Rozpoczęto prowadzenie sprawy',id,cid);persist();closeSheet();clientMode='Sprawy';caseTab='Przegląd';go('case',cid)}
function caseSettings(id){const c=caseBy(id);openSheet('Ustawienia sprawy',`<form onsubmit="saveCaseSettings(event,${id})">${inputField('Nazwa sprawy','title',c.title)}${selectField('Status','status',['W toku','Oczekujemy na klienta','Zamknięta'],c.status)}${selectField('Prowadzący','owner',['Tomasz','Paweł'],c.owner)}${textareaField('Zakres sprawy','summary',c.summary)}<p class="field-help">Status sprawy nie usuwa zaplanowanych terminów ani zadań.</p>${formFooter('Zapisz zmiany')}</form>`)}
function saveCaseSettings(e,id){const f=fields(e);if(!f.title.trim()||!f.summary.trim())return formError('Nazwa i zakres nie mogą być puste.');Object.assign(caseBy(id),{title:f.title.trim(),summary:f.summary.trim(),status:f.status,owner:f.owner});record(`Zaktualizowano sprawę: ${f.status}`,caseBy(id).personId,id);persist();closeSheet();render()}
function noteForm(pid,cid=null,text=''){openSheet('Notatka z rozmowy',`<p class="form-caption">${esc(person(pid).name)}${cid?' · '+caseBy(cid).number:''}</p><form onsubmit="saveNote(event,${pid},${cid})">${textareaField('Ustalenia','note',text)}<button type="button" class="secondary full" onclick="dictate('field-note','pl-PL')">${ic('mic')} Podyktuj notatkę</button><p id="dictation-status" class="field-status" role="status"></p>${formFooter('Zapisz notatkę')}</form>`)}
function addNote(pid,cid,text){data.notes.push({id:nextId(),personId:pid,caseId:cid,text:text.trim(),author:data.user,date:TODAY});record('Dodano notatkę z rozmowy',pid,cid);persist()}
function saveNote(e,pid,cid){const f=fields(e);if(!f.note.trim())return formError('Wpisz lub podyktuj treść notatki.');addNote(pid,cid,f.note);closeSheet();render();toast('Notatka zapisana w karcie klienta.')}
function taskForm(pid=null,cid=null,taskId=null){const t=data.tasks.find(t=>t.id===taskId);openSheet(t?'Edytuj zadanie':'Nowe zadanie',`<form onsubmit="saveTask(event,${taskId})">${inputField('Co trzeba zrobić?','title',t?.title||'')}${selectField('Powiązany klient','personId',[['','Bez klienta'],...data.people.map(p=>[p.id,p.name])],t?.personId??pid??'')}<div class="form-columns">${selectField('Odpowiedzialny','owner',['Tomasz','Paweł'],t?.owner||data.user)}${inputField('Termin','date',t?.date||TODAY,'date')}</div>${selectField('Priorytet','priority',['Zwykłe','Pilne'],t?.priority||'Zwykłe')}${formFooter(t?'Zapisz zadanie':'Dodaj zadanie')}</form>`)}
function saveTask(e,id){const f=fields(e);if(!f.title.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(f.date))return formError('Uzupełnij nazwę i prawidłową datę.');const pid=f.personId===''?null:Number(f.personId);if(pid!==null&&!person(pid))return formError('Wybierz klienta z listy.');const payload={title:f.title.trim(),personId:pid,caseId:pid===null?null:(data.tasks.find(t=>t.id===id)?.personId===pid?data.tasks.find(t=>t.id===id).caseId:linkedCase(pid)?.id??null),owner:f.owner,date:f.date,priority:f.priority};const old=data.tasks.find(t=>t.id===id);if(old)Object.assign(old,payload);else data.tasks.push({...payload,id:nextId(),done:false});record(`${old?'Zmieniono':'Dodano'} zadanie: ${payload.title}`,pid,payload.caseId);persist();closeSheet();render();toast('Zadanie zapisane.')}
function taskDetail(id){const t=data.tasks.find(t=>t.id===id);openSheet('Zadanie',`<h3>${esc(t.title)}</h3><div class="info-list"><div><span>Termin</span><b>${dateText(t.date)}</b></div><div><span>Odpowiedzialny</span><b>${t.owner}</b></div><div><span>Status</span><b>${t.done?'Wykonane':'Do zrobienia'}</b></div></div><button class="primary" onclick="toggleTask(${id});closeSheet()">${ic('check')} ${t.done?'Przywróć zadanie':'Oznacz jako wykonane'}</button><div class="button-row"><button class="secondary" onclick="taskForm(null,null,${id})">${ic('edit')} Edytuj</button>${t.personId!==null?`<button class="secondary" onclick="go('${t.caseId?'case':'person'}',${t.caseId??t.personId})">${ic('folder')} ${t.caseId?'Sprawa':'Klient'}</button>`:''}</div>`)}
function eventForm(pid=null,cid=null,id=null){const e=eventBy(id);openSheet(e?'Edytuj termin':'Nowy termin',`<form onsubmit="saveEvent(event,${id})">${selectField('Klient','personId',data.people.map(p=>[p.id,p.name]),e?.personId??pid??data.people[0].id)}${inputField('Nazwa wydarzenia','title',e?.title||'Konsultacja')}${selectField('Rodzaj','type',['Konsultacja','Termin w sprawie'],e?.type||'Konsultacja')}<div class="form-columns">${inputField('Data','date',e?.date||(screen==='calendar'?day:TODAY),'date')}${inputField('Godzina','time',e?.time||'15:00','time')}</div><div class="form-columns">${selectField('Czas trwania','duration',[[30,'30 minut'],[60,'60 minut'],[90,'90 minut'],[120,'120 minut']],e?.duration||30)}${selectField('Prowadzący','owner',['Tomasz','Paweł'],e?.owner==='Nieprzypisany'?data.user:e?.owner||data.user)}</div>${inputField('Miejsce lub forma','place',e?.place||'Online')}${selectField('Status','status',['Do potwierdzenia','Potwierdzona','Zakończona'],e?.status||'Do potwierdzenia')}${formFooter(e?'Zapisz termin':'Dodaj termin')}</form>`)}
function overlapping(candidate,ignoreId=null){const minutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));return data.events.find(e=>e.id!==ignoreId&&e.date===candidate.date&&e.owner===candidate.owner&&e.status!=='Zakończona'&&candidate.status!=='Zakończona'&&minutes(e.time)<minutes(candidate.time)+candidate.duration&&minutes(candidate.time)<minutes(e.time)+e.duration)}
function saveEvent(e,id){const f=fields(e),pid=Number(f.personId);if(!person(pid)||!f.title.trim()||!f.place.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(f.date)||!/^\d{2}:\d{2}$/.test(f.time))return formError('Uzupełnij klienta, nazwę, miejsce i prawidłowy termin.');const next={personId:pid,caseId:eventBy(id)?.personId===pid?eventBy(id).caseId:linkedCase(pid)?.id??null,title:f.title.trim(),date:f.date,time:f.time,duration:Number(f.duration),owner:f.owner,type:f.type,status:f.status,place:f.place.trim()};const conflict=overlapping(next,id);if(conflict)return formError(`${next.owner} ma już wydarzenie o ${conflict.time}: ${conflict.title}. Wybierz inną godzinę lub prowadzącego.`);const old=eventBy(id);if(old)Object.assign(old,next);else data.events.push({...next,id:nextId()});record(`${old?'Zmieniono':'Dodano'} termin: ${next.title}, ${next.date} ${next.time}`,pid,next.caseId);persist();closeSheet();render();toast('Termin zapisany. Nie wysłano powiadomienia do klienta.')}
function eventDetail(id){const e=eventBy(id),p=person(e.personId),c=e.caseId?caseBy(e.caseId):null;openSheet(e.type,`${personRow(p,e.title,false)}<div class="info-list"><div><span>Kiedy</span><b>${dateText(e.date)}, ${e.time}</b></div><div><span>Czas</span><b>${e.duration} min</b></div><div><span>Miejsce</span><b>${esc(e.place)}</b></div><div><span>Prowadzący</span><b>${esc(e.owner)}</b></div><div><span>Status</span><b>${esc(e.status)}</b></div></div>${e.status==='Zakończona'?`<button class="primary" onclick="noteForm(${p.id},${e.caseId})">${ic('edit')} Dodaj notatkę po spotkaniu</button>`:`<button class="primary" onclick="openEmma(${p.id},'case')">${ic('spark')} Przygotuj mnie z Emmą</button>`}<div class="button-row"><button class="secondary" onclick="eventForm(null,null,${id})">${ic('edit')} Zmień termin</button><button class="secondary" onclick="go('chat',${p.id})">${ic('chat')} WhatsApp</button></div>${e.status==='Do potwierdzenia'?`<button class="secondary full" onclick="confirmEvent(${id})">${ic('check')} Potwierdź konsultację</button>`:e.status==='Potwierdzona'?`<button class="secondary full" onclick="finishEvent(${id})">${ic('check')} Oznacz spotkanie jako zakończone</button>`:''}${c?`<button class="text-button" onclick="go('case',${c.id})">Otwórz sprawę ${c.number} ${ic('chevron')}</button>`:`<button class="text-button" onclick="caseForm(${p.id})">Rozpocznij prowadzenie sprawy ${ic('chevron')}</button>`}`)}
function confirmEvent(id){const e=eventBy(id);if(e.owner==='Nieprzypisany'){eventForm(null,null,id);formError('Wybierz prowadzącego i status „Potwierdzona”, aby potwierdzić konsultację.');return}if(overlapping({...e,status:'Potwierdzona'},id)){eventForm(null,null,id);formError('Termin koliduje z innym wydarzeniem prowadzącego.');return}e.status='Potwierdzona';record('Potwierdzono termin: '+e.title,e.personId,e.caseId);persist();render();eventDetail(id);toast('Termin potwierdzony w kalendarzu.')}
function finishEvent(id){const e=eventBy(id);e.status='Zakończona';record('Zakończono spotkanie: '+e.title,e.personId,e.caseId);persist();render();eventDetail(id)}
function emmaPage(){const p=emmaContext===null?null:person(emmaContext),c=p?linkedCase(p.id):null,urgent=waiting().find(x=>x.urgent);return `${heading('TWÓJ ASYSTENT','Emma',`<button class="icon-button" onclick="toggleSpeech()" aria-pressed="${speakReplies}" aria-label="${speakReplies?'Wyłącz':'Włącz'} odpowiedzi głosowe">${ic('sound')}</button>`)}<button class="emma-context" onclick="chooseContext()">${ic(p?'folder':'globe')}<span>${p?esc(p.name)+(c?' · '+c.number:''):'Cała kancelaria'}</span>${ic('chevron')}</button>${!emmaTurns.length?`<div class="emma-intro"><div class="orb big-orb" id="voice-orb"></div><h2>${p?'Jestem w kontekście tej sprawy.':'Od czego zaczynamy?'}</h2><p>${p?`${esc(p.topic)}.<br>Mam pod ręką ustalenia, zadania i terminy.`:urgent?`${urgent.name.split(' ')[0]} czeka na odpowiedź.<br>Mogę pomóc Ci przygotować się do rozmowy.`:'Mogę omówić plan, sprawę lub kolejne zadanie.'}</p></div><div class="emma-suggestions"><button onclick="assistantExample('${p?'case':'brief'}')">${ic('sound')}<span>${p?'Podsumuj tę sprawę':'Opowiedz mi o dzisiejszym dniu'}<small>${p?'Kontekst, notatki i otwarte zadania':'Konsultacje i rzeczy do załatwienia'}</small></span>${ic('chevron')}</button><button onclick="assistantExample('reply')">${ic('chat')}<span>Przygotuj odpowiedź<small>W języku klienta, do sprawdzenia</small></span>${ic('chevron')}</button><button onclick="assistantExample('task')">${ic('tasks')}<span>Dodaj kolejne zadanie<small>Przypisz osobę i termin</small></span>${ic('chevron')}</button></div>`:`<div class="emma-conversation">${emmaTurns.map(renderTurn).join('')}</div>`}<div class="voice-status-line" role="status" id="voice-status">${esc(voiceMessage||'Możesz mówić lub napisać polecenie.')}</div>${emmaTurns.length&&!pendingAction?`<div class="small-suggestions"><button onclick="assistantExample('note')">${ic('edit')} Notatka</button><button onclick="assistantExample('task')">${ic('tasks')} Zadanie</button><button onclick="assistantExample('reply')">${ic('chat')} Odpowiedź</button></div>`:''}<p class="demo-foot">Emma działa na przykładowych scenariuszach.</p>`}
function renderTurn(t){if(t.type==='action'){const p=t.personId===null?null:person(t.personId);return `<article class="emma-action"><div class="emma-action-heading"><span>${ic(t.kind==='reply'?'chat':t.kind==='note'?'edit':'tasks')} ${t.kind==='reply'?'Wiadomość':t.kind==='note'?'Notatka':'Zadanie'}</span>${chip(t.state==='done'?'Wykonano':t.state==='cancelled'?'Anulowano':'Do sprawdzenia',t.state==='done'?'green':'')}</div><h3>${p?esc(p.name):'Kancelaria'}</h3>${t.kind==='task'?`<p class="action-meta">${esc(t.owner)} · ${dateText(t.date)}</p>`:''}${t.state==='pending'?`<textarea class="draft" aria-label="Edytuj treść działania" oninput="editAction(${t.id},this.value)">${esc(t.text)}</textarea><div class="button-row"><button class="secondary" onclick="speakAction(${t.id})">${ic('sound')} Odsłuchaj</button><button class="secondary" onclick="cancelAction(${t.id})">Anuluj</button></div><button id="approve-action-${t.id}" class="primary full" onclick="approveAction(${t.id})" ${!t.text.trim()?'disabled':''}>${ic('check')} ${t.kind==='reply'?'Zatwierdź wiadomość':t.kind==='note'?'Zapisz notatkę':'Dodaj zadanie'}</button>`:`<p class="action-text">${esc(t.text)}</p>${t.state==='done'?`<button class="text-button" onclick="${t.kind==='reply'?`go('chat',${t.personId})`:t.kind==='note'?`go('${t.caseId?'case':'person'}',${t.caseId??t.personId})`:"go('tasks')"}">Zobacz rezultat ${ic('chevron')}</button>`:''}`}</article>`}return `<div class="emma-turn ${t.role==='user'?'from-user':''}"><span>${t.role==='user'?'Ty':'Emma'}</span><p>${esc(t.text)}</p>${t.role!=='user'?`<button class="listen-text" onclick="readTurn(${t.id})">${ic('sound')} Odsłuchaj</button>`:''}</div>`}
function dock(){const ch=$('#chat-dock');ch.hidden=screen!=='chat';ch.innerHTML=screen==='chat'?chatComposer():'';const h=$('#chat-header');h.hidden=screen!=='chat';h.innerHTML=screen==='chat'?chatHeader():'';const d=$('#assistant-dock');d.hidden=screen!=='emma';d.innerHTML=screen==='emma'?`<div class="voice-controls-row"><span id="dock-state">${voiceState==='listening'?'Słucham…':voiceState==='speaking'?'Emma mówi…':speakReplies?'Rozmowa głosowa':'Odpowiedzi tekstowe'}</span><button class="text-button" onclick="stopVoice();paintVoice()">${ic('pause')} Przerwij</button></div><form class="assistant-compose" onsubmit="submitEmma(event)"><button type="button" class="mic-button" onclick="startVoice()" aria-label="Rozpocznij lub zakończ wypowiedź" aria-pressed="${voiceState==='listening'}">${ic(voiceState==='listening'?'check':'mic')}</button><input id="emma-text" aria-label="Polecenie dla Emmy" placeholder="Napisz do Emmy…" value="${esc(emmaInput)}" oninput="emmaInput=this.value" autocomplete="off"><button class="send-button" aria-label="Przekaż polecenie">${ic('arrow')}</button></form>`:''}
function openEmma(pid=null,action=null,start=false){emmaContext=pid;awaitingInput=null;go('emma');if(action)assistantExample(action);if(start)startVoice()}
function chooseContext(action=null){openSheet('Wybierz kontekst Emmy',`<div class="choice-list">${!action?'<button onclick="setEmmaContext(null)"><span>Cała kancelaria</span>'+ic('globe')+'</button>':''}${data.people.map(p=>`<button onclick="setEmmaContext(${p.id},${action?`'${action}'`:'null'})"><span>${esc(p.name)}<small>${esc(p.topic)}</small></span>${ic('chevron')}</button>`).join('')}</div>`)}
function setEmmaContext(id,action=null){emmaContext=id;awaitingInput=null;closeSheet();render();if(action)assistantExample(action)}
function addTurn(role,text){emmaTurns.push({id:nextId(),role,text})}
function refreshEmma(){render();if(screen==='emma')requestAnimationFrame(()=>{const target=$('.emma-conversation')?.lastElementChild;target?.scrollIntoView({block:'nearest',behavior:'auto'})})}
function answer(text,read=true){addTurn('assistant',text);refreshEmma();if(read&&speakReplies)speak(text)}
function briefing(){const events=sortEvents(data.events.filter(e=>e.date===TODAY&&e.status!=='Zakończona')),tasks=openTasks().filter(t=>t.date<=TODAY);return `Dzisiaj w zespole: ${plural(events.length,'wydarzenie','wydarzenia','wydarzeń')}. ${events.map(e=>`${e.time}: ${person(e.personId).name}, ${e.title}. Prowadzący: ${e.owner}. ${e.status==='Do potwierdzenia'?'Termin czeka na potwierdzenie.':''}`).join('\n')}\n\nDo załatwienia: ${tasks.length?tasks.map(t=>t.title+' ('+t.owner+')').join('; '):'brak otwartych zadań na dziś'}.\n${waiting().length?`Na odpowiedź czekają: ${waiting().map(p=>p.name).join(', ')}.`:'Wszystkie rozmowy zaopiekowane.'}`}
function caseSummary(pid){const p=person(pid),c=linkedCase(pid),notes=data.notes.filter(n=>n.personId===pid),tasks=openTasks().filter(t=>t.personId===pid),events=sortEvents(data.events.filter(e=>e.personId===pid&&e.date>=TODAY&&e.status!=='Zakończona'));return `${p.name}. ${c?c.title+'. Status: '+c.status+'. Prowadzący: '+c.owner+'.':p.topic+'. Zgłoszenie: '+p.stage+'.'}\n\n${c?c.summary:p.description}\n\n${notes.length?'Ostatnia notatka: '+notes.at(-1).text:'Nie ma jeszcze notatki z rozmowy.'}\n\n${events.length?'Najbliższy termin: '+dateText(events[0].date).toLowerCase()+', '+events[0].time+'. '+events[0].title+'. '+events[0].status+'.':'Brak kolejnego terminu.'}\n\n${tasks.length?'Otwarte zadania: '+tasks.map(t=>t.title+' ('+t.owner+')').join('; ')+'.':'Nie ma otwartych zadań.'}`}
function assistantExample(action){stopVoice();if(action==='brief'){addTurn('user','Podsumuj dzisiejszy dzień.');answer(briefing());return}if(pendingAction){answer('Najpierw zatwierdź albo anuluj przygotowane działanie.');return}if(emmaContext===null){chooseContext(action);return}const p=person(emmaContext);if(action==='case'){addTurn('user','Przygotuj mnie do rozmowy: '+p.name+'.');answer(caseSummary(p.id));return}if(action==='reply'){addTurn('user','Przygotuj odpowiedź do '+p.name+'.');prepareReply(p.id);return}if(action==='note'||action==='task'){addTurn('user',action==='note'?'Chcę zapisać notatkę.':'Chcę dodać zadanie.');awaitingInput={kind:action,personId:p.id};answer(action==='note'?`Co zapisać w notatce dla ${p.name}? Podyktuj lub wpisz treść.`:`Jakie zadanie dodać dla ${p.name}? Wpisz lub podyktuj treść. Przygotuję je na dziś dla Ciebie; osobę i termin możesz zmienić po zapisaniu.`)}}
function draftText(pid){const p=person(pid),e=sortEvents(data.events.filter(e=>e.personId===pid&&e.status!=='Zakończona'))[0];if(pid===1)return 'Доброго дня. Отримав Ваше звернення щодо затримання брата. Будь ласка, повідомте, де він перебуває, та надішліть наявні документи. Після уточнення обставин узгодимо подальший контакт.';if(p.locale==='uk-UA')return `Доброго дня! ${e?`Бачу нашу консультацію о ${e.time}. ${e.status==='Potwierdzona'?'Зустріч підтверджена.':'Час ще очікує на підтвердження.'}`:'Отримав Ваше звернення.'} Будь ласка, надішліть документи перед розмовою.`;if(p.locale==='ru-RU')return `Здравствуйте! Да, консультацию можно провести на русском языке. ${e?`Вижу Вашу запись на ${e.date} в ${e.time}. ${e.status==='Potwierdzona'?'Встреча подтверждена.':'Время ещё ожидает подтверждения.'}`:'Сообщите, пожалуйста, удобное время для разговора.'}`;return `Dziękuję za wiadomość. ${e?`Widzę termin ${e.date}, godz. ${e.time}. ${e.status==='Potwierdzona'?'Spotkanie jest potwierdzone.':'Termin oczekuje jeszcze na potwierdzenie.'}`:'Proszę o podanie dogodnego terminu kontaktu.'}`}
function newAction(kind,pid,text){if(pendingAction)return;const a={id:nextId(),type:'action',kind,personId:pid,caseId:pid===null?null:linkedCase(pid)?.id??null,text,owner:data.user,date:TODAY,state:'pending'};pendingAction=a;emmaTurns.push(a);awaitingInput=null;refreshEmma();return a}
function prepareReply(pid){newAction('reply',pid,draftText(pid));if(speakReplies)speak(`Przygotowałam wiadomość do ${person(pid).name}. Sprawdź treść lub odsłuchaj ją przed zatwierdzeniem.`)}
function editAction(id,text){const a=emmaTurns.find(t=>t.id===id);if(a?.state==='pending'){a.text=text;const b=$('#approve-action-'+id);if(b)b.disabled=!text.trim()}}
function approveAction(id){const a=emmaTurns.find(t=>t.id===id);if(!a||a.state!=='pending'||!a.text.trim())return;stopVoice();if(a.kind==='reply')sendMessage(a.personId,a.text.trim());else if(a.kind==='note')addNote(a.personId,a.caseId,a.text);else{data.tasks.push({id:nextId(),personId:a.personId,caseId:a.caseId,title:a.text.trim(),owner:a.owner,date:a.date,done:false,priority:'Zwykłe'});record('Dodano zadanie z Emmą: '+a.text.trim(),a.personId,a.caseId);persist()}a.state='done';pendingAction=null;answer(a.kind==='reply'?'Wiadomość dodana do rozmowy. Wysyłka jest symulowana.':a.kind==='note'?'Notatka jest już w karcie klienta.':'Zadanie jest już na wspólnej liście.')}
function cancelAction(id){const a=emmaTurns.find(t=>t.id===id);if(a?.state!=='pending')return;a.state='cancelled';pendingAction=null;stopVoice();answer('Anulowałam działanie.')}
function resolvePerson(text){const x=text.toLocaleLowerCase('pl');const names=data.people.filter(p=>p.name.toLocaleLowerCase('pl').split(/\s+/).some(n=>n.length>=4&&x.includes(n.slice(0,Math.max(4,n.length-2)))));if(names.length>1)return 'multiple';if(names.length===1)return names[0].id;if(/(?:odpow\S*|wiadomo\S*|notatk\S*|spraw\S*)[\s\S]*?\b(?:do|dla|klienta)\s+(?!mnie\b|niego\b|niej\b|tej\b|tego\b)\p{L}/u.test(x))return 'unknown';return emmaContext}
function submitEmma(e){e.preventDefault();const text=$('#emma-text').value;emmaInput='';handleCommand(text)}
function handleCommand(raw){const text=raw.trim();if(!text)return;stopVoice();addTurn('user',text);const x=text.toLocaleLowerCase('pl');if(/^(anuluj|rezygnuję)[.! ]*$/.test(x)){if(pendingAction)cancelAction(pendingAction.id);else{awaitingInput=null;answer('Anulowano. Możemy przejść do kolejnego polecenia.')}return}if(/^(zatwierdź|wyślij|zapisz|tak)[.! ]*$/.test(x)){if(pendingAction)approveAction(pendingAction.id);else answer('Nie ma przygotowanego działania do zatwierdzenia.');return}if(pendingAction){answer('Działanie czeka na zatwierdzenie. Możesz je poprawić, odsłuchać albo anulować.');return}if(awaitingInput){newAction(awaitingInput.kind,awaitingInput.personId,text);if(speakReplies)speak('Przygotowałam treść do zatwierdzenia.');return}if(/plan|dzisiejsz|dzień|dniu|kalendarz/.test(x)&&!/notatk|wiadomo|odpow|zadani/.test(x)){answer(briefing());return}const id=resolvePerson(text);if(id==='multiple'||id==='unknown'){answer(id==='multiple'?'Wybierz jednego klienta w polu kontekstu. Polecenie dotyczy kilku osób.':'Nie rozpoznałam wskazanego klienta. Wybierz go w polu kontekstu.');return}const kind=/notatk/.test(x)?'note':/zadani|przypomnij/.test(x)?'task':/odpow|wiadomo/.test(x)?'reply':/podsum|przygotuj|spraw/.test(x)?'case':null;if(!kind){answer('W prototypie mogę omówić dzień lub sprawę, przygotować wiadomość, notatkę i zadanie. Wybierz skrót albo podaj klienta i polecenie.');return}if(id===null&&kind!=='task'){answer('Wybierz klienta w polu kontekstu, żeby powiązać z nim polecenie.');return}emmaContext=id;if(kind==='case'){answer(caseSummary(id));return}const colon=text.indexOf(':');if(colon>=0&&text.slice(colon+1).trim()){newAction(kind,id,text.slice(colon+1).trim());if(kind==='task'){pendingAction.date=/jutro/.test(x)?addDays(TODAY,1):TODAY;refreshEmma()}if(speakReplies)speak('Treść jest gotowa. Sprawdź ją i zatwierdź.');return}if(kind==='reply'){prepareReply(id);return}awaitingInput={kind,personId:id};answer(kind==='note'?'Podyktuj treść notatki.':'Podyktuj treść zadania. Domyślnie przypiszę je Tobie na dziś.')}
function readTurn(id){const t=emmaTurns.find(t=>t.id===id);if(t)speak(t.text)}function speakAction(id){const a=emmaTurns.find(t=>t.id===id);if(a)speak(a.text,a.kind==='reply'?person(a.personId).locale:'pl-PL')}
function toggleSpeech(){speakReplies=!speakReplies;stopVoice();render()}
function profile(){openSheet('Twój obszar pracy',`<h3>Kancelaria Rogoża</h3><div class="choice-list">${['Tomasz','Paweł'].map(n=>`<button onclick="switchUser('${n}')"><span>${n} Rogoża</span>${data.user===n?ic('check'):ic('chevron')}</button>`).join('')}</div><p class="field-help">AI i integracja WhatsApp są symulowane. Głos korzysta z funkcji przeglądarki. Data przykładowego dnia: 11 września 2026.</p><button class="secondary full" onclick="resetPrompt()">Przywróć dane przykładowe</button>`)}
function switchUser(n){data.user=n;persist();closeSheet();render()}
function resetPrompt(){openSheet('Przywrócić dane przykładowe?',`<p>Usuniesz zmiany, wiadomości, notatki, sprawy i zadania dodane w tej sesji prototypu.</p><div class="button-row"><button class="secondary" onclick="profile()">Wróć</button><button class="primary" onclick="resetDemo()">Przywróć dane</button></div>`)}
function resetDemo(){stopVoice();data=structuredClone(initial);ensureChats();chatSearch='';chatFilter='Wszystkie';firstUnreadId=null;emmaTurns=[];pendingAction=null;emmaContext=null;awaitingInput=null;history=[];persist();closeSheet();go('home',null,false)}
function render(){ensureChats();$('.iphone-preview').classList.toggle('chat-open',screen==='chat');syncChatViewport();$('.phone').classList.toggle('in-chat',screen==='chat');nav();$('#content').innerHTML=({home,clients,person:personPage,case:casePage,tasks:tasksPage,calendar,messages:messagesPage,chat:chatPage,emma:emmaPage}[screen])();dock();paintVoice()}
function syncChatViewport(){if(window.visualViewport)$('.phone').style.setProperty?.('--chat-viewport',window.visualViewport.height+'px')}
function stopVoice(){voiceToken++;speechToken++;clearTimeout(voiceTimer);if(rec){const old=rec;rec=null;old.onend=null;old.onresult=null;old.onerror=null;try{old.abort()}catch{}}if(window.speechSynthesis)window.speechSynthesis.cancel();voiceState='ready';voiceMessage='';paintVoice()}
function paintVoice(){const s=$('#voice-status');if(s)s.textContent=voiceMessage||({listening:'Słucham Cię. Dotknij mikrofonu, żeby zakończyć.',speaking:'Emma mówi. Możesz przerwać i zabrać głos.',requesting:'Uruchamiam mikrofon…',ready:'Możesz mówić lub napisać polecenie.',error:'Możesz kontynuować tekstem.'}[voiceState]);const orb=$('#voice-orb');if(orb)orb.classList.toggle('listening',['listening','speaking','requesting'].includes(voiceState));const state=$('#dock-state');if(state)state.textContent=voiceState==='listening'?'Słucham…':voiceState==='speaking'?'Emma mówi…':speakReplies?'Rozmowa głosowa':'Odpowiedzi tekstowe';const mic=$('.mic-button');if(mic){mic.setAttribute('aria-pressed',voiceState==='listening');mic.innerHTML=ic(voiceState==='listening'?'check':'mic')}}
function recognize(lang,live,done,field=false){const R=window.SpeechRecognition||window.webkitSpeechRecognition;const status=text=>{voiceMessage=text;paintVoice();if(field&&$('#dictation-status'))$('#dictation-status').textContent=text};if(!R){voiceState='error';status('Dyktowanie nie jest dostępne w tej przeglądarce. Wpisz tekst.');return}const token=++voiceToken;let transcript='',failed=false;voiceState='requesting';paintVoice();const r=new R();rec=r;r.lang=lang;r.interimResults=true;r.continuous=false;r.onstart=()=>{if(token!==voiceToken)return;voiceState='listening';status('Słucham. Dotknij mikrofonu, żeby zakończyć.');voiceTimer=setTimeout(()=>{if(rec===r)r.stop()},45000)};r.onresult=e=>{if(token!==voiceToken)return;transcript=Array.from(e.results).map(x=>x[0].transcript).join(' ').trim();live(transcript)};r.onerror=e=>{if(token!==voiceToken)return;failed=true;voiceState='error';status(e.error==='not-allowed'?'Brak dostępu do mikrofonu. Zmień uprawnienia strony lub wpisz tekst.':e.error==='no-speech'?'Nie usłyszałam wypowiedzi. Spróbuj ponownie.':'Nie udało się rozpoznać mowy. Wpisz tekst lub spróbuj ponownie.')};r.onend=()=>{clearTimeout(voiceTimer);if(token!==voiceToken)return;rec=null;if(failed)return;voiceState='ready';if(transcript){status(field?'Transkrypcja gotowa. Sprawdź treść przed zapisaniem.':'Przygotowuję odpowiedź…');done(transcript)}else status('Nie zarejestrowano wypowiedzi.')};try{r.start()}catch{voiceState='error';rec=null;status('Nie udało się uruchomić mikrofonu. Możesz wpisać tekst.')}}
function startVoice(){if(rec&&voiceState==='listening'){rec.stop();return}stopVoice();recognize('pl-PL',text=>{emmaInput=text;if($('#emma-text'))$('#emma-text').value=text},text=>{emmaInput='';handleCommand(text)})}
function dictate(id,lang){if(rec&&voiceState==='listening'){rec.stop();return}const input=$('#'+id);if(!input)return;const prefix=input.value.trim();stopVoice();recognize(lang,text=>{if(input.isConnected){input.value=[prefix,text].filter(Boolean).join(' ');input.dispatchEvent(new Event('input',{bubbles:true}))}},()=>{if(input.isConnected)input.focus()},true)}
function speak(text,lang='pl-PL'){stopVoice();if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){voiceState='error';voiceMessage='Odsłuch nie jest dostępny. Odpowiedź możesz przeczytać.';paintVoice();return}const token=++speechToken,u=new window.SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.97;u.onstart=()=>{if(token!==speechToken)return;voiceState='speaking';paintVoice()};u.onend=()=>{if(token!==speechToken)return;voiceState='ready';voiceMessage='Możesz odpowiedzieć głosem lub tekstem.';paintVoice()};u.onerror=e=>{if(token!==speechToken||['interrupted','canceled'].includes(e.error))return;voiceState='error';voiceMessage='Odsłuch się nie powiódł. Treść jest dostępna na ekranie.';paintVoice()};window.speechSynthesis.speak(u)}
$('#sheet').addEventListener('cancel',e=>{e.preventDefault();closeSheet()});$('#sheet').addEventListener('click',e=>{if(e.target!==$('#sheet'))return;const r=$('#sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSheet()});window.addEventListener('resize',()=>{if($('#sheet').open)placeSheet()});window.visualViewport?.addEventListener('resize',()=>{syncChatViewport();if($('#sheet').open)placeSheet();if(screen==='chat')scrollChat()});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice()});render();for(const p of data.people)for(const m of data.messages[p.id]||[])if(['sending','sent'].includes(m.status)){const snapshot=data;setTimeout(()=>{if(data===snapshot)advanceReceipt(p.id,m.id,'delivered')},1500)}
