import * as THREE from 'three';
import {makeGeometry} from './relief.js';
import {poseAt} from './animation.js';
import './style.css';
const canvas=document.querySelector('canvas'),frame=document.querySelector('.portrait'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const query=new URLSearchParams(location.search);
let state='waiting',level=0;
const states=new Set(['waiting','listening','thinking','speaking','interrupted']);
if(states.has(query.get('state')))state=query.get('state');
if(Number.isFinite(Number(query.get('level'))))level=THREE.MathUtils.clamp(Number(query.get('level')),0,1);
let previewUntil=0;
window.emma={setState(s){if(states.has(s)){state=s;previewUntil=0;}},setAudioLevel(v){level=Number.isFinite(v)?THREE.MathUtils.clamp(v,0,1):0;},getState:()=>state,previewAnimation(){previewUntil=performance.now()+15000;}};
frame.setAttribute('role','button');frame.tabIndex=0;
frame.setAttribute('aria-label','Emma — dotknij, aby obejrzeć animację demonstracyjną');
frame.title='Podgląd animacji, bez uruchamiania mikrofonu';
frame.onclick=()=>window.emma.previewAnimation();
frame.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();window.emma.previewAnimation();}};
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,20);camera.position.z=3.65;
let renderer,loaded=false;
try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0,0);}catch{canvas.hidden=true;}
const loader=new THREE.TextureLoader();
const texture=loader.load('/emma-avatar-refined.png',()=>{loaded=true;},undefined,()=>{canvas.hidden=true;});
const blinkTexture=loader.load('/emma-blink-overlay.png'),speakTexture=loader.load('/emma-speak-overlay.png');
for(const map of [texture,blinkTexture,speakTexture])map.colorSpace=THREE.SRGBColorSpace;
const expression={blink:{value:0},speak:{value:0},gaze:{value:new THREE.Vector2()}};
const material=new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false});
material.onBeforeCompile=shader=>{
 shader.uniforms.emmaBlink=expression.blink;shader.uniforms.emmaSpeak=expression.speak;shader.uniforms.emmaGaze=expression.gaze;
 shader.uniforms.emmaBlinkMap={value:blinkTexture};shader.uniforms.emmaSpeakMap={value:speakTexture};
 shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nuniform sampler2D emmaBlinkMap; uniform sampler2D emmaSpeakMap; uniform float emmaBlink; uniform float emmaSpeak; uniform vec2 emmaGaze;');
 shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`vec4 originalEmma=texture2D(map,vMapUv);
  float leftEye=1.0-smoothstep(0.72,1.0,length((vMapUv-vec2(.383,.592))/vec2(.102,.088)));
  float rightEye=1.0-smoothstep(0.72,1.0,length((vMapUv-vec2(.594,.577))/vec2(.102,.088)));
  float eyeMask=max(leftEye,rightEye);
  vec4 gazeEmma=texture2D(map,vMapUv-emmaGaze);
  originalEmma.rgb=mix(originalEmma.rgb,gazeEmma.rgb,eyeMask*.82);
  vec4 blinkEmma=texture2D(emmaBlinkMap,vMapUv);
  float mouthMask=1.0-smoothstep(.7,1.0,length((vMapUv-vec2(.5,.365))/vec2(.18,.105)));
  vec4 speakEmma=texture2D(emmaSpeakMap,vMapUv);
  originalEmma.rgb=mix(originalEmma.rgb,blinkEmma.rgb,blinkEmma.a*emmaBlink);
  originalEmma.rgb=mix(originalEmma.rgb,speakEmma.rgb,speakEmma.a*emmaSpeak);
  diffuseColor*=originalEmma;`);
};
const mesh=new THREE.Mesh(makeGeometry(),material);scene.add(mesh);
let targetX=0,targetY=0;
canvas.onpointermove=e=>{const b=canvas.getBoundingClientRect();targetX=((e.clientX-b.left)/b.width-.5)*.09;targetY=((e.clientY-b.top)/b.height-.5)*.05;};canvas.onpointerleave=()=>{targetX=targetY=0;};
new ResizeObserver(()=>{if(renderer){const {width,height}=frame.getBoundingClientRect();renderer.setSize(width,height,false);}}).observe(frame);
let last=0,time=0;const frozenTime=query.has('time')?Number(query.get('time')):NaN;
function animate(now){requestAnimationFrame(animate);if(!renderer||document.hidden||now-last<1000/30)return;const dt=Math.min((now-last)/1000,.05);last=now;const paused=reduced.matches;if(!paused)time+=dt;
if(Number.isFinite(frozenTime))time=frozenTime;
const preview=now<previewUntil,remaining=(previewUntil-now)/1000;
const demoState=remaining>10?'listening':remaining>6?'thinking':'speaking';
const current=preview?demoState:state;
const pose=poseAt(time,current,preview&&current==='speaking'?.35+.3*Math.sin(time*5)**2:level),ease=1-Math.exp(-dt*7);
mesh.rotation.y+=((paused?0:targetX+pose.y)-mesh.rotation.y)*ease;
mesh.rotation.x+=((paused?0:targetY+pose.x)-mesh.rotation.x)*ease;
mesh.rotation.z+=((paused?0:pose.z)-mesh.rotation.z)*ease;
mesh.scale.setScalar(paused?1:pose.breath);
expression.blink.value=paused?0:Math.max(pose.morphs[0],pose.morphs[1]);
expression.speak.value=paused?0:pose.morphs[4];expression.gaze.value.set(paused?0:pose.gazeX,paused?0:pose.gazeY);
mesh.morphTargetInfluences.forEach((value,i)=>{const target=i===2||i===3?pose.morphs[i]:0;mesh.morphTargetInfluences[i]=paused?0:value+(target-value)*ease;});
if(loaded){renderer.render(scene,camera);document.querySelector('#fallback').style.visibility='hidden';}}
requestAnimationFrame(animate);
const dialog=document.querySelector('dialog');
function explain(title,copy){document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-copy').textContent=copy;dialog.showModal();}
document.querySelector('#voice').onclick=()=>{window.emma.setState('listening');explain('Podgląd rozmowy','Emma przechodzi w stan słuchania. Ten osobny prototyp nie uruchamia mikrofonu ani prawdziwej rozmowy. W aplikacji stan będzie pochodził z istniejącej sesji głosowej.');};
dialog.onclose=()=>window.emma.setState('waiting');
document.querySelector('#write').onclick=()=>explain('Napisz do Emmy','To podgląd wyglądu awatara. Czat pozostaje w istniejącej aplikacji.');
document.querySelector('#today').onclick=()=>explain('Zadania na dziś','Lista zadań pozostaje w istniejącej aplikacji.');
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>explain(b.textContent.replace('3','').trim(),'Nawigacja pozostaje w istniejącej aplikacji. Ten ekran służy do oceny Emmy w miejscu orba.'));
